import { Config } from "@/types/config";

export const config: Config = {
    title: "TailGrads",
    prodUrl: "https://tailgrads.vercel.app",
    email: "addevelopment.pro@gmail.com",
    keywords: [
        "TailGrads",
        "Tailwind CSS",
        "Gradient Generator",
        "Beautiful Gradients",
        "Awesome Gradients",
        "Gradient Creator",
        "Web Design Tool",
        "CSS Gradient Tool",
        "Color Gradients",
        "Gradient Editor",
        "Tailwind Gradient Utility",
        "Gradient Palette",
        "Gradient Design",
        "Gradient Color Picker",
        "CSS Gradient Generator",
        "Web Development Tool",
        "Tailwind CSS Gradient Generator",
        "Gradient Backgrounds",
        "Gradient Texts",
        "Gradient Color Scheme",
        "Tailwind Gradient Builder",
    ],
};
